version: 2
updates:
  - directory: /
    package-ecosystem: bundler
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: all
    schedule:
      interval: monthly
    open-pull-requests-limit: 50
    groups:
      ruby:
        patterns:
          - '*'
    commit-message:
      prefix: Dependabot
